# Generated by Django 4.2.7 on 2023-11-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("ubicacion", models.CharField(max_length=100)),
                ("contacto", models.EmailField(max_length=200)),
                ("fecha_creacion", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "tiendas_buenos_aires",
            },
        ),
    ]
